trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7'

- script: terraform init
- script: terraform validate
- script: terraform plan
- script: terraform apply -auto-approve