- name: Start App
  run: |
    nohup java -jar target/*.jar > app.log 2>&1 &
    sleep 40
  working-directory: ./app

- name: Show Logs
  run: cat app.log
  working-directory: ./app

- name: Wait for App
  run: |
    for i in {1..10}; do
      curl http://localhost:8080 && exit 0
      echo "Waiting..."
      sleep 5
    done
    exit 1