name: Java CI Test + DB Connection

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: employeedb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: |
          cd app
          mvn clean package -DskipTests

      - name: Start App
        run: |
          cd app
          nohup java -jar target/*.jar > app.log 2>&1 &
          sleep 40
          cat app.log

      - name: Wait for App
        run: |
          for i in {1..12}; do
            echo "Attempt $i..."
            curl -f http://localhost:8080 && exit 0
            sleep 5
          done
          exit 1

      - name: Test POST API
        run: |
          curl -X POST http://localhost:8080/api/employees \
          -H "Content-Type: application/json" \
          -d '{"name":"Ajay","email":"ajay@test.com","department":"DevOps","salary":50000}'

      - name: Test GET API
        run: |
          curl http://localhost:8080/api/employees